resources:
- name: exporter-sources
  type: git
  source: 
    uri: https://github.com/emerald-squad/uptime_apdex_aggregate_exporter.git
    branch: 'master'

- name: github
  type: github-release
  source:
    user: emerald-squad
    repository: uptime_apdex_aggregate_exporter
    access_token: {{github-access-token}}

- name: version
  type: semver
  source :
    driver: git
    branch: version
    file: number
    initial_version: 1.0.0
    uri: git@github.com:emerald-squad/uptime_apdex_aggregate_exporter.git
    private_key: {{git-key}}

jobs:
- name: build-and-release
  plan:
  - get: exporter-sources
    trigger: true
  - get: version
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: '1.9'
      run:
        path: sh
        args:
        - -cxe
        - |
          VERSION=$(cat version/number)
          pushd exporter-sources
          make
          tar -czvf graphite_exporter-${VERSION}.linux-amd64.tar.gz uptime-apdex-aggregate-exporter-linux-amd64
          popd
          mv exporter-sources/graphite_exporter-${VERSION}.linux-amd64.tar.gz archive/
          exit 1
      inputs:
      - name: exporter-sources
      - name: version
      outputs:
      - name: archive